version: "3.8"
services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rates
    image: postgres:13.5-alpine
    networks:
      - default
    ports:
      - 5432:5432       # 5432 was already occupied in my host and I wanted to test it.
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "rates", "-U", "postgres" ]
      timeout: 60s
      interval: 30s
      retries: 20
    volumes:
      - ./db/rates.sql:/docker-entrypoint-initdb.d/rates.sql

  app :
    build: ./rates/
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy